### ISSUE TITLE
Play a video larger than 3GB

### ISSUE THREAD

**Issue by snowinszu** [jhiesey/videostream#38] opened 2017-08-17 08:58 UTC
I tried to play a MP4 video larger than 3GB, but it doesn't work.

![wechatimg1086](https://user-images.githubusercontent.com/14010277/29404281-342dc2e8-836d-11e7-88e9-336fb97168d0.jpeg)

**Comment by tzarebczan** [comment] 2018-07-23 21:31
We are having the same issue on the LBRY project (https://github.com/lbryio/lbry-desktop/issues/1577)

Anyone interested in working on fixing this? We can help pay for dev time with LBC (LBRY Credits)

**Comment by jhiesey** [comment] 2018-07-24 07:06
I'll do some preliminary investigation this week.

**Comment by diegocr** [comment] 2018-07-24 19:57
Hi @jhiesey,

Let me help out with this since you was very kind by looking into adding Safari browser support (although is not yet complete ;))

The main issue here is a off-by-one-byte bug in the [uint64be](https://github.com/mafintosh/uint64be) package, so first of all you need to update your package.json file to use the 2.0.2 version.

Then you will need to add a `co64` box parser in `mp4-box-encoding`, you can grab one already made [here](https://github.com/meganz/videostream/blob/755095d5f803ab9caba622b7196e4dfcf946fd1c/mp4-remuxer.js#L606-L625).

and finally:

https://github.com/jhiesey/videostream/blob/48f375057341d06075a49dd44c5f8c9813c81f13/mp4-remuxer.js#L155

Replace that `stbl.stco` by `(stbl.stco || stbl.co64)`, and that's all :)

**Comment by jhiesey** [comment] 2018-07-24 21:42
Woah thanks for the debugging @diegocr! I'll get those fixes merged in this week.

**Comment by diegocr** [comment] 2018-07-25 20:13
No problem, i can make PRs if you want, but these changes should be kinda straightforward :)

**Closed** 2018-07-28 23:21 UTC

**Comment by diegocr** [comment] 2018-08-01 04:40
@tzarebczan Thanks for the offer, I don't like taking any tips for this though, if there were some allocated to me don't hesitate to forward them towards this repo author/owner :)

**Comment by tzarebczan** [comment] 2018-08-07 14:59
@diegocr / @jhiesey can you confirm this was fixed? I tried pulling in the changes and still seeing this: 
![image](https://user-images.githubusercontent.com/8120721/43783926-e9176724-9a30-11e8-80df-f01926874a9c.png)

**Comment by diegocr** [comment] 2018-08-12 18:28
Well, these changes definitely added support for _"big files"_ by integrating such `co64` parser, and i can confirm it does work like a charm for me, although i don't use render-media.

**Comment by jhiesey** [comment] 2018-08-13 07:25
Yes I verified the changes fixed the large file issue. This looks like a different problem; I'm a bit busy at the moment but will take a look when I have time.
